name: CI

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display the environment variables and their values
        run: |
          node -v
        shell: bash
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: Jellyfin.wgt
      #     path: output/Jellyfin.wgt
